version: '3'
services:
  nginx:
    platform: linux/amd64
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - mysql
    image: php:7.4-fpm

  # db:
  #   platform: linux/amd64
  #   image: mysql:5.7
  #   ports:
  #     - 13306:3306
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #     - ./mysql/sql:/docker-entrypoint-initdb.d
  #     - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - mysql

  mysql:
    # platform: linux/amd64
    image: mysql:latest
    # image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    # volumes::
    #   - ./docker/mysql:/docker-entrypoint-initdb.d   
    environment:
      MYSQL_DATABASE: quizydb
      MYSQL_USER: karen
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf